window.usaiiDemoData = {
  profile: {
    name: 'Maya Demo Student',
    level: 'undergraduate',
    interests: ['responsible AI', 'education', 'career readiness', 'data storytelling'],
    goals: [
      'choose a realistic AI portfolio project',
      'build proof for an internship',
      'avoid generic career advice',
    ],
    skills: {
      python: 58,
      data_analysis: 64,
      frontend: 46,
      product_thinking: 72,
      responsible_ai: 67,
      communication: 78,
      experiment_design: 52,
    },
    constraints: ['8 hours per week', 'needs low-cost tools', 'wants human review before outreach'],
  },
  opportunities: [
    {
      id: 'learning_analytics_assistant',
      title: 'Learning analytics assistant for first-year students',
      category: 'education',
      signals: ['responsible AI', 'education', 'data storytelling'],
      required_skills: {
        python: 62,
        data_analysis: 72,
        frontend: 55,
        responsible_ai: 75,
        experiment_design: 65,
      },
      portfolio_artifact: 'A privacy-safe dashboard comparing study habits, confidence, and next actions.',
    },
    {
      id: 'career_readiness_copilot',
      title: 'Career readiness copilot for scholarship and internship prep',
      category: 'career',
      signals: ['career readiness', 'education', 'responsible AI'],
      required_skills: {
        frontend: 58,
        product_thinking: 76,
        responsible_ai: 72,
        communication: 80,
        data_analysis: 62,
      },
      portfolio_artifact: 'A verified plan, portfolio rubric, and outreach-safe opportunity shortlist.',
    },
    {
      id: 'community_data_story',
      title: 'Community data story for local opportunity gaps',
      category: 'social impact',
      signals: ['data storytelling', 'career readiness'],
      required_skills: {
        data_analysis: 70,
        communication: 82,
        product_thinking: 68,
        experiment_design: 60,
      },
      portfolio_artifact: 'A public story that explains one access gap and a student-led intervention.',
    },
  ],
  planSteps: [
    ['Decision baseline', 'Confirm the student goal, constraints, target role, and success rubric.', 'Goal statement plus rubric snapshot.'],
    ['Skill-gap sprint', 'Practice the top two missing skills with one artifact per skill.', 'Two artifacts and self-rating deltas.'],
    ['Portfolio artifact', 'Build and explain the selected portfolio artifact.', 'Portfolio page and transparent model notes.'],
    ['Opportunity match', 'Map the artifact to internships, scholarships, clubs, or research openings.', 'Shortlist and outreach-safe draft.'],
  ],
  guardrails: [
    'Synthetic demo personas unless a real student opts in.',
    'No protected-trait inference or worth-ranking.',
    'Recommendation reasons show weak evidence and missing inputs.',
    'Outreach and public portfolio changes remain human-approved.',
    'No jobs, admissions, scholarship, or award guarantees.',
  ],
  readiness: {
    prod: 100,
    qualifier: 'ready',
    studentGate: '2-5 eligible students',
    deadline: '2026-06-21 23:59 ET',
    finalSubmit: false,
  },
};
